using Content.Client.UserInterface.Controls;
using Content.Shared.PolygonRenderer;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Robust.Shared.Timing;

namespace Content.Client.PolygonRenderer;

[GenerateTypedNameReferences]
public sealed partial class BoxTestWindow : FancyWindow
{
    [Dependency] private readonly IPrototypeManager _prototype = default!;
    [Dependency] private readonly IGameTiming _timing = default!;

    internal static readonly ProtoId<PolygonModelPrototype> BoxId = "TestBox";
    internal PolygonModel Box;

    internal const float UpdateRate = 1f / 30f;
    internal float Accumulator;

    public BoxTestWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        Box = _prototype.Index(BoxId);
    }

    protected override void Draw(DrawingHandleScreen handle)
    {
        base.Draw(handle);

        Accumulator -= (float)_timing.FrameTime.TotalSeconds;
        if (Accumulator > 0f)
            return;

        Accumulator = MathF.Max(0f, Accumulator + UpdateRate);

        var newBox = new PolygonModel();

        foreach (var polygon in Box.Polygons)
        {
            if (polygon.Color == null)
                continue;

            var newVertices = new Vector3[3];

            for (var i = 0; i < 3; i++)
                newVertices[i] = Vector3.Transform(polygon.Vertices[i], Matrix4.CreateRotationX(UpdateRate));

            newBox.Polygons.Add(new Polygon(newVertices));
        }

        var modelArray = new PolygonModel[1];
        modelArray[0] = newBox;
        Renderer.Models = modelArray;
    }
}
