using Content.Client.UserInterface.Controls;
using Content.Shared.PolygonRenderer;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Robust.Shared.Timing;

namespace Content.Client.PolygonRenderer;

[GenerateTypedNameReferences]
public sealed partial class BoxTestWindow : FancyWindow
{
    [Dependency] private readonly IPrototypeManager _prototype = default!;
    [Dependency] private readonly IGameTiming _timing = default!;

    internal static readonly ProtoId<PolygonModelPrototype> BoxId = "TestBox";
    internal PolygonModel Box;

    internal const float UpdateRate = 1f / 30f;
    internal float Accumulator;

    internal float Rotation = 0f;

    internal static readonly Vector3 Camera = new()
    {
        X = -1,
        Y = -1,
        Z = -2
    };

    public BoxTestWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        Box = _prototype.Index(BoxId);
    }

    protected override void Draw(DrawingHandleScreen handle)
    {
        base.Draw(handle);

        Accumulator -= (float)_timing.FrameTime.TotalSeconds;
        if (Accumulator > 0f)
            return;

        Accumulator = MathF.Max(0f, Accumulator + UpdateRate);
        Rotation += UpdateRate;

        var newBox = new PolygonModel();
        newBox.Polygons = Box.Polygons;
        newBox.Rotation = new(Rotation, 0f, Rotation * 0.5f);
        newBox.Scale = new(Accumulator * 32f);

        var modelArray = new PolygonModel[1];
        modelArray[0] = newBox;
        Renderer.Models = modelArray;
        Renderer.Camera = Camera;
    }
}
