using Content.Client.UserInterface.Controls;
using Content.Shared.PolygonRenderer;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Robust.Shared.Timing;

namespace Content.Client.PolygonRenderer;

[GenerateTypedNameReferences]
public sealed partial class BoxTestWindow : FancyWindow
{
    [Dependency] private readonly IPrototypeManager _prototype = default!;
    [Dependency] private readonly IGameTiming _timing = default!;

    private static readonly ProtoId<PolygonModelPrototype> BoxId = "TestBox";
    private readonly PolygonModel _box;

    private const uint BoxCount = 3;
    private const float SpacePerBox = 0.25f;

    private const float UpdateRate = 1f / 30f;
    private float _accumulator;

    private float _rotation = 0f;

    private static readonly Vector3 Camera = new()
    {
        X = -1,
        Y = -1,
        Z = -2
    };

    public BoxTestWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _box = _prototype.Index(BoxId);
    }

    protected override void Draw(DrawingHandleScreen handle)
    {
        base.Draw(handle);

        _accumulator -= (float)_timing.FrameTime.TotalSeconds;
        if (_accumulator > 0f)
            return;

        _accumulator = MathF.Max(0f, _accumulator + UpdateRate);
        _rotation += UpdateRate;

        var modelArray = new PolygonModel[BoxCount];
        for (var i = 0; i < BoxCount; i++)
            modelArray[i] = NewBox(i);

        Renderer.Models = modelArray;
        Renderer.Camera = Camera;
    }

    private PolygonModel NewBox(int index)
    {
        var newBox = new PolygonModel(_box.Polygons);

        var offset = index;
        if ((index & 1) == 1)
            offset += 1;

        var rotation = new Vector3(_rotation * offset, index, _rotation * offset * 0.5f);
        var position = new Vector3(SpacePerBox * offset, 0f, 0f);

        if ((index & 1) == 1)
            position *= -1;

        newBox.Rotation = rotation;
        newBox.Position = position;

        return newBox;
    }
}
