using Content.Shared.Surgery.Components;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.Surgery.UI;

[GenerateTypedNameReferences]
public abstract partial class BaseSurgeryReceiverButton : Button
{
    public ISurgeryReceiver Receiver;

    public BaseSurgeryReceiverButton(ISurgeryReceiver receiver)
    {
        RobustXamlLoader.Load(this);

        Receiver = receiver;
    }
}
