using Content.Shared.Body.Part;
using Content.Shared.Surgery.Components;
using Content.Shared.Surgery.Systems;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;

namespace Content.Client.Surgery.UI;

[GenerateTypedNameReferences]
public sealed partial class SurgeryLimbButton : Button
{
    private static readonly ResPath IconRsi = new("/Textures/Interface/Actions/zone_sel.rsi");

    public ISurgeryReceiver Receiver;

    public SurgeryLimbButton(ISurgeryReceiver receiver, BodyPart bodyPart, SpriteSystem sprite)
    {
        RobustXamlLoader.Load(this);

        Receiver = receiver;
        Label.Text = Loc.GetString(SurgeryHelper.GetBodyPartLoc(bodyPart));
        Icon.Texture = sprite.Frame0(new SpriteSpecifier.Rsi(IconRsi, SurgeryHelper.BodyPartIconState(bodyPart)));
    }
}
