using Content.Shared.Surgery;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client.Surgery.UI;

[GenerateTypedNameReferences]
public sealed partial class SurgerySurgeryButton : Button
{
    public ProtoId<SurgeryPrototype> Surgery;

    public SurgerySurgeryButton(ProtoId<SurgeryPrototype> surgeryId)
    {
        RobustXamlLoader.Load(this);

        Surgery = surgeryId;
        Text = surgeryId;
    }
}
