using Content.Shared.Body.Part;
using Content.Shared.Surgery;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.Surgery.UI;

[GenerateTypedNameReferences]
public sealed partial class SurgeryNodeDetailsTab : PanelContainer
{
    public SurgeryNodeDetailsTab(SurgerySpecial special, EntityUid receiver, EntityUid? body, EntityUid? limb, BodyPart? part, SpriteSystem sprite) : base()
    {
        RobustXamlLoader.Load(this);

        if (special.Name(receiver, body, limb, part, out var name))
            Name = name;

        if (special.GetIcon(receiver, body, limb, part, out var icon))
            SpecialIcon.Texture = sprite.Frame0(icon);

        if (special.Description(receiver, body, limb, part, out var description))
            SpecialDescription.Text = description;
    }
}
