using Content.Shared.Body.Part;
using Content.Shared.Surgery;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.Surgery.UI;

[GenerateTypedNameReferences]
public sealed partial class SurgeryNodeDetailsTab : PanelContainer
{
    public SurgeryNodeDetailsTab(SurgerySpecial special, EntityUid receiver, EntityUid? body, EntityUid? limb, BodyPart part, SpriteSystem sprite) : base()
    {
        RobustXamlLoader.Load(this);

        Name = special.Name(receiver, body, limb, part);

        var icon = special.GetIcon(receiver, body, limb, part);
        SpecialIcon.Texture = icon == null ? null : sprite.Frame0(icon);
        SpecialDescription.Text = special.Description(receiver, body, limb, part);
    }
}
