using Content.Shared.Body.Part;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.Surgery.UI;

[GenerateTypedNameReferences]
public sealed partial class SurgeryLimbButton : Button
{
    public SurgeryLimbButton(BodyPart bodyPart)
    {
        RobustXamlLoader.Load(this);
        Text = $"{bodyPart.Type}-{bodyPart.Side}";
    }
}
