using Content.Shared.Surgery;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.Surgery.UI;

[GenerateTypedNameReferences]
public sealed partial class SurgeryNodeDetails : PanelContainer
{
    public SurgeryNodeDetails(SurgeryNode node) : base()
    {
        RobustXamlLoader.Load(this);
    }
}
