using Content.Shared.Body.Part;
using Content.Shared.Surgery;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.Surgery.UI;

[GenerateTypedNameReferences]
public sealed partial class SurgeryEdgeDetails : PanelContainer
{
    public SurgeryEdgeDetails(SurgeryEdge edge, EntityUid? body, EntityUid? limb, BodyPart part) : base()
    {
        RobustXamlLoader.Load(this);

        RequirementDescription.Text = edge.Requirement.Description(body, limb, part);
    }
}
