using Content.Shared.Surgery;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client.Surgery.UI;

[GenerateTypedNameReferences]
public sealed partial class SurgerySurgeryButton : Button
{
    public ProtoId<SurgeryPrototype> Surgery;

    public SurgerySurgeryButton(ProtoId<SurgeryPrototype> surgeryId, IPrototypeManager prototype)
    {
        RobustXamlLoader.Load(this);

        Surgery = surgeryId;
        var surgery = prototype.Index(surgeryId);

        Text = Loc.GetString(surgery.Name);
        ToolTip = Loc.GetString(surgery.Description);
    }
}
