using Content.Shared.Surgery;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;

namespace Content.Client.Surgery.UI;

[GenerateTypedNameReferences]
public sealed partial class SurgeryNodeDetails : PanelContainer
{
    public SurgeryNodeDetails(SurgeryNode node) : base()
    {
    }
}
