using Content.Shared.Surgery.Components;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.Surgery.UI;

[GenerateTypedNameReferences]
public sealed partial class SurgerySurgeryButton : Button
{
    public SurgerySurgeryButton(ISurgeryReceiver surgery)
    {
        RobustXamlLoader.Load(this);
        Text = surgery.GetHashCode().ToString();
    }
}
