using Content.Shared.Body.Part;
using Content.Shared.Surgery.Components;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.Surgery.UI;

[GenerateTypedNameReferences]
public sealed partial class SurgeryLimbButton : Button
{
    public ISurgeryReceiver Receiver;

    public SurgeryLimbButton(ISurgeryReceiver receiver, BodyPart bodyPart)
    {
        RobustXamlLoader.Load(this);

        Receiver = receiver;
        Text = $"{bodyPart.Type}-{bodyPart.Side}";
    }
}
