using Content.Shared.Teleportation.Components;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.Telescience.Ui;

[GenerateTypedNameReferences]
public sealed partial class TeleframeConsoleBeaconButton : Button
{
    public TeleframeConsoleBeaconButton(TeleportPoint beacon)
    {
        RobustXamlLoader.Load(this);

        Text = beacon.Location;
    }
}
