- type: cargoProduct
  id: SecurityArmor
  icon:
    sprite: Clothing/OuterClothing/Armor/bulletproof.rsi
    state: icon
  data: !type:CargoProductItemData
    product: CrateSecurityArmor
  cost: 1250
  category: cargoproduct-category-name-security
  group: market

- type: cargoProduct
  id: SecurityHelmet
  icon:
    sprite: Clothing/Head/Helmets/security.rsi
    state: icon
  data: !type:CargoProductItemData
    product: CrateSecurityHelmet
  cost: 550
  category: cargoproduct-category-name-security
  group: market

- type: cargoProduct
  id: SecurityNonLethal
  icon:
    sprite: Objects/Weapons/Guns/Battery/disabler.rsi
    state: base
  data: !type:CargoProductItemData
    product: CrateSecurityNonlethal
  cost: 4000
  category: cargoproduct-category-name-security
  group: market

- type: cargoProduct
  id: SecuritySupplies
  icon:
    sprite: Objects/Storage/boxes.rsi
    state: box_security
  data: !type:CargoProductItemData
    product: CrateSecuritySupplies
  cost: 500
  category: cargoproduct-category-name-security
  group: market

- type: cargoProduct
  id: SecurityRestraints
  icon:
    sprite: Objects/Misc/handcuffs.rsi
    state: handcuff
  data: !type:CargoProductItemData
    product: CrateRestraints
  cost: 1000
  category: cargoproduct-category-name-security
  group: market

- type: cargoProduct
  id: SecurityBiosuit
  icon:
    sprite: Clothing/Head/Hoods/Bio/security.rsi
    state: icon
  data: !type:CargoProductItemData
    product: CrateSecurityBiosuit
  cost: 800
  category: cargoproduct-category-name-security
  group: market

- type: cargoProduct
  id: SecurityBarrier
  icon:
    sprite: Objects/Specific/Security/barrier.rsi
    state: idle
  data: !type:CargoProductItemData
    product: DeployableBarrier
  cost: 1000
  category: cargoproduct-category-name-security
  group: market

- type: cargoProduct
  id: SecurityNonlethalThrowables
  icon:
    sprite: Objects/Weapons/Grenades/stingergrenade.rsi
    state: icon
  data: !type:CargoProductItemData
    product: CrateSecNonlethalThrowables
  cost: 2500
  category: cargoproduct-category-name-security
  group: market

- type: cargoProduct
  id: SecurityGenPopCloset
  icon:
    sprite: Structures/Storage/closet.rsi
    state: genpop
  data: !type:CargoProductItemData
    product: LockerPrisoner
  cost: 250
  category: cargoproduct-category-name-security
  group: market
