using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.Silicons.Sync;

[GenerateTypedNameReferences]
public sealed partial class SiliconSyncMonitoringSlaveButton : PanelContainer
{
    [Dependency] private readonly IEntityManager _entity = default!;

    public SiliconSyncMonitoringSlaveButton(EntityUid slave)
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        SlaveLabel.Text = _entity.GetComponent<MetaDataComponent>(slave).EntityName;
        SlaveIcon.SetEntity(slave);
    }
}
