using Content.Shared.NameIdentifier;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.Silicons.Sync;

[GenerateTypedNameReferences]
public sealed partial class SiliconSyncMonitoringSlaveButton : PanelContainer
{
    [Dependency] private readonly IEntityManager _entity = default!;

    public SiliconSyncMonitoringSlaveButton(EntityUid slave)
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        if (_entity.TryGetComponent<NameIdentifierComponent>(slave, out var nameIdentifierComponent))
        {
            var fullName = _entity.GetComponent<MetaDataComponent>(slave).EntityName;
            var name = fullName.Substring(0, fullName.Length - nameIdentifierComponent.FullIdentifier.Length - 1);
            SlaveLabel.Text = name + "\n" + nameIdentifierComponent.FullIdentifier;
        }
        else
        {
            var name = _entity.GetComponent<MetaDataComponent>(slave).EntityName;
            SlaveLabel.Text = name;
        }

        SlaveIcon.SetEntity(slave);
    }
}
