using Content.Client.UserInterface.Controls;
using Content.Shared.Prototypes;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility;
using System.Linq;

namespace Content.Client.Silicons.Sync;

[GenerateTypedNameReferences]
public sealed partial class SiliconSyncMonitoringWindow : FancyWindow
{
    [Dependency] private readonly IEntityManager _entity = default!;
    [Dependency] private readonly IPrototypeManager _prototype = default!;
    private readonly SpriteSystem _sprite = default!;

    public SiliconSyncMonitoringWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _sprite = _entity.System<SpriteSystem>();
    }

    public void ShowSlaves(Dictionary<NetEntity, HashSet<NetEntity>> masterSlaves, Dictionary<NetEntity, ProtoId<NavMapBlipPrototype>> slaveBlips, EntityUid console)
    {
        NavMap.TrackedEntities.Clear();
        NavMap.Owner = console;
        NavMap.MapUid = _entity.GetComponent<TransformComponent>(console).GridUid;

        Dictionary<EntityUid, HashSet<EntityUid>> slaveMasters = [];

        foreach (var (masterNet, slaves) in masterSlaves)
        {
            var master = _entity.GetEntity(masterNet);

            foreach (var slaveNet in slaves)
            {
                var slave = _entity.GetEntity(slaveNet);
                if (slaveMasters.ContainsKey(slave))
                    continue;

                slaveMasters.Add(slave, [master]);

                if (!slaveBlips.TryGetValue(slaveNet, out var blipId))
                    continue;

                if (!_prototype.TryIndex(blipId, out var blip))
                    continue;

                if (blip.TexturePaths == null || !blip.TexturePaths.Any())
                    continue;

                var slavePos = _entity.GetComponent<TransformComponent>(slave).Coordinates;
                var blipTexture = _sprite.Frame0(new SpriteSpecifier.Texture(blip.TexturePaths[0]));

                NavMap.TrackedEntities.Add(slaveNet, new(slavePos, blipTexture, blip.Color, blip.Blinks, true, blip.Scale));
            }
        }

        foreach (var (slave, masters) in slaveMasters)
        {
        }
    }
}
