using Content.Shared.Modules.ModSuit.UI.Modules;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.Modules.ModSuit.Modules;

[GenerateTypedNameReferences, Virtual]
public partial class ModSuitModuleBaseModulePanel : PanelContainer
{
    [Dependency] private readonly IEntityManager _entity = default!;

    public ModSuitModuleBaseModulePanel(NetEntity netModule, ModSuitModuleBaseModuleBuiEntry buiEntry)
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        var module = _entity.GetEntity(netModule);
        ModuleIcon.SetEntity(module);
        ModuleName.Text = _entity.GetComponent<MetaDataComponent>(module).EntityName;
    }
}
