using Content.Shared.Arcade.Racer;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.Arcade.Racer;

[GenerateTypedNameReferences]
public sealed partial class RacerEditorControl : Control
{
    public RacerEditorControl() : base()
    {
        RobustXamlLoader.Load(this);
    }

    public void SetEditorData(RacerGameStageEditorData data)
    {
        Editor.SetData(data);
    }
}
