using Content.Shared.Arcade.Racer.Stage;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility;

namespace Content.Client.Arcade.Racer;

[GenerateTypedNameReferences]
public sealed partial class RacerEditorViewportEditNodePopupAddConnectionPopup : RacerEditorViewportPopup
{
    public event Action<IRacerArcadeStageEdge>? OnAddConnection;

    public RacerEditorViewportEditNodePopupAddConnectionPopup(RacerArcadeStageGraph graph, IPrototypeManager prototype) : base()
    {
        RobustXamlLoader.Load(this);

        StageButton.OnPressed += _ =>
        {
            var edge = new RacerArcadeStageEdgeStage()
            {
                StageId = string.Empty
            };

            var popup = new RacerEditorViewportEditEdgeStagePopup(edge, prototype);
            popup.OnEdgeModified += args =>
            {
                OnAddConnection?.Invoke(args);
                Close();
            };
            OpenPopup(popup);
        };

        NodeButton.OnPressed += _ =>
        {
            var edge = new RacerArcadeStageEdgeNode()
            {
                ConnectionId = string.Empty,
                ControlPoints = [],
                Width = 1f,
                Texture = new SpriteSpecifier.Rsi(new ResPath("/Textures/Interface/Racer/road.rsi"), "paved-stripe"),
            };

            var popup = new RacerEditorViewportEditEdgeNodePopup(edge, graph);
            popup.OnEdgeModified += args =>
            {
                OnAddConnection?.Invoke(args);
                Close();
            };
            OpenPopup(popup);
        };
    }
}
