using Content.Shared.Arcade.Racer;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility;

namespace Content.Client.Arcade.Racer;

[GenerateTypedNameReferences]
public sealed partial class RacerEditorViewportEdgeTextureButton : TextureButton
{
    [Dependency] private readonly IEntityManager _entity = default!;
    [Dependency] private readonly IPrototypeManager _prototype = default!;
    private readonly SpriteSystem _sprite;

    private static readonly SpriteSpecifier FallbackTexture = new SpriteSpecifier.Rsi(new("/Textures/Interface/Racer/road.rsi"), "fallback");

    public event Action<RacerEditorViewportEdgeTextureButtonPopup>? OnPopupCreated;
    public event Action<RacerEditorViewportEdgeTextureButtonPopup>? OnPopupRemoved;
    public event Action<ProtoId<RacerGameEdgeTexturePrototype>>? OnTextureSelected;

    public RacerEditorViewportEdgeTextureButton() : base()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _sprite = _entity.System<SpriteSystem>();

        var popup = new RacerEditorViewportEdgeTextureButtonPopup(_prototype, _sprite);
        popup.OnTextureSelected += args =>
        {
            OnTextureSelected?.Invoke(args);
            SetTexture(args);
            OnPopupRemoved?.Invoke(popup);
        };
        OnPressed += _ => OnPopupCreated?.Invoke(popup);
    }

    public void SetTexture(ProtoId<RacerGameEdgeTexturePrototype>? id)
    {
        var texture = id == null ? _sprite.Frame0(FallbackTexture) : _sprite.Frame0(_prototype.Index(id).Texture);
        TextureNormal = texture;
    }
}
