using Content.Shared.Arcade.Racer;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;
using System.Numerics;

namespace Content.Client.Arcade.Racer;

[GenerateTypedNameReferences]
public sealed partial class RacerEditorControl : Control
{
    public RacerEditorControl() : base()
    {
        RobustXamlLoader.Load(this);

        ViewReset.OnPressed += _ =>
        {
            Editor.SetScale(Vector2.One);
            Editor.SetOffset(Vector2.Zero);
        };

        Editor.OnGraphOffsetChanged += (offset, scale) =>
        {
            GraphOffset.Text = Loc.GetString("racer-editor-graph-offset-info",
                ("offsetX", $"{offset.X:N2}"), ("offsetY", $"{offset.Y:N2}"),
                ("scaleX", $"{scale.X:N3}"), ("scaleY", $"{scale.Y:N3}")
            );
        };

        Editor.OnGridSizeChanged += grid =>
        {
            GridSize.Text = Loc.GetString("racer-editor-grid-size-info",
                ("size", grid)
            );
        };

        Editor.OnMousePosChanged += pos =>
        {
            MousePosition.Text = Loc.GetString("racer-editor-mouse-pos-info",
                ("X", $"{pos.X:N2}"), ("Y", $"{pos.Y:N2}")
            );
        };

        // so the above label has text on initial spawn
        // this fucking sucks but this whole tool only exists for my convenience
        Editor.SetScale(Vector2.One);
        Editor.SetOffset(Vector2.Zero);
    }

    public void SetEditorData(RacerGameStageEditorData data)
    {
        Editor.SetData(data);
    }

}
