using Content.Shared.Arcade.Racer.Stage;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client.Arcade.Racer;

[GenerateTypedNameReferences]
public sealed partial class RacerEditorViewportEditNodePopupConnection : BoxContainer
{
    public event Action? OnRemoveConnection;

    public event Action<RacerEditorViewportPopup>? OnAddPopup;

    public event Action<IRacerArcadeStageEdge>? OnConnectionModified;

    public RacerEditorViewportEditNodePopupConnection(IRacerArcadeStageEdge connection, string nodeId, RacerArcadeStageGraph graph, IPrototypeManager prototype) : base()
    {
        RobustXamlLoader.Load(this);

        EditConnection.OnPressed += _ =>
        {
            var popup = connection switch
            {
                RacerArcadeStageEdgeNode edgeNode => CreateNodePopup(edgeNode, nodeId, graph),
                RacerArcadeStageEdgeStage edgeStage => CreateStagePopup(edgeStage, prototype),
                _ => throw new NotImplementedException()
            };

            OnAddPopup?.Invoke(popup);
        };

        RemoveConnection.OnPressed += _ => OnRemoveConnection?.Invoke();
    }

    private RacerEditorViewportPopup CreateNodePopup(RacerArcadeStageEdgeNode edge, string nodeId, RacerArcadeStageGraph graph)
    {
        var popup = new RacerEditorViewportEditEdgeNodePopup(edge, nodeId, graph);
        popup.OnEdgeModified += args => OnConnectionModified?.Invoke(args);
        return popup;
    }

    private RacerEditorViewportPopup CreateStagePopup(RacerArcadeStageEdgeStage edge, IPrototypeManager prototype)
    {
        var popup = new RacerEditorViewportEditEdgeStagePopup(edge, prototype);
        popup.OnEdgeModified += args => OnConnectionModified?.Invoke(args);
        return popup;
    }
}
