using Content.Shared.Arcade.Racer;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.Arcade.Racer;

[GenerateTypedNameReferences]
public sealed partial class RacerEditorViewportEdgeTextureButtonPopupButton : TextureButton
{
    public RacerEditorViewportEdgeTextureButtonPopupButton(RacerGameEdgeTexturePrototype edgeTexture, SpriteSystem sprite) : base()
    {
        RobustXamlLoader.Load(this);

        var texture = sprite.Frame0(edgeTexture.Texture);
        TextureNormal = texture;

        ToolTip = edgeTexture.ID;
    }
}
