using Content.Shared.Arcade.Racer;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client.Arcade.Racer;

[GenerateTypedNameReferences]
public sealed partial class RacerEditorViewportEdgeTextureButtonPopup : RacerEditorViewportPopup
{
    public event Action<ProtoId<RacerGameEdgeTexturePrototype>>? OnTextureSelected;

    public RacerEditorViewportEdgeTextureButtonPopup(IPrototypeManager prototype, SpriteSystem sprite) : base()
    {
        RobustXamlLoader.Load(this);

        foreach (var edgeTexture in prototype.EnumeratePrototypes<RacerGameEdgeTexturePrototype>())
        {
            var button = new RacerEditorViewportEdgeTextureButtonPopupButton(edgeTexture, sprite);
            button.OnPressed += _ => OnTextureSelected?.Invoke(edgeTexture.ID);
            Grid.AddChild(button);
        }
    }
}
