using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.Arcade.Racer;

[GenerateTypedNameReferences]
public sealed partial class RacerEditorViewportNewNodePopup : Popup
{
    public event Action<string>? OnNewNodeName;

    public RacerEditorViewportNewNodePopup() : base()
    {
        RobustXamlLoader.Load(this);

        OnPopupOpen += Input.GrabKeyboardFocus;

        Input.OnTextEntered += args =>
        {
            OnNewNodeName?.Invoke(args.Text);
            Close();
        };
    }
}
