using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.Arcade.Racer;

[GenerateTypedNameReferences]
public sealed partial class RacerEditorViewportNewNodePopup : RacerEditorViewportPopup
{
    public event Action<string>? OnNewNodeName;

    public RacerEditorViewportNewNodePopup() : base()
    {
        RobustXamlLoader.Load(this);

        Input.GrabKeyboardFocus();

        Input.OnTextEntered += args =>
        {
            OnNewNodeName?.Invoke(args.Text);
            Close();
        };
    }
}
