using Content.Client.UserInterface.Controls;
using Content.Shared.Arcade.Racer.Components;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.Arcade.Racer;

[GenerateTypedNameReferences]
public sealed partial class RacerGameWindow : FancyWindow
{
    public RacerGameWindow() : base()
    {
        RobustXamlLoader.Load(this);
    }

    public void SetCabinet(Entity<RacerArcadeComponent> cabinet, EntityUid viewer)
    {
        Viewport.SetCabinet(cabinet, viewer);
    }
}
