using Content.Shared.Arcade.Racer.Stage;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using System.Linq;

namespace Content.Client.Arcade.Racer;

[GenerateTypedNameReferences]
public sealed partial class RacerEditorViewportEditNodePopup : RacerEditorViewportPopup
{
    public event Action<RacerArcadeStageNode>? OnNodeEdited;

    public RacerEditorViewportEditNodePopup(string id, RacerArcadeStageNode node, RacerArcadeStageGraph graph, IPrototypeManager prototype) : base()
    {
        RobustXamlLoader.Load(this);

        NodeId.Text = id;
        NodePosition.Text = Loc.GetString("racer-editor-edit-node-position", ("X", node.Position.X), ("Y", node.Position.Y));

        RefreshConnectionControls(node, id, graph, prototype);

        NodeAddConnection.OnPressed += _ =>
        {
            var popup = new RacerEditorViewportEditNodePopupAddConnectionPopup(graph, id, prototype);
            popup.OnAddConnection += connection =>
            {
                node.Connections.Add(connection);
                RefreshConnectionControls(node, id, graph, prototype);
            };
            OpenPopup(popup);
        };
    }

    private void RefreshConnectionControls(RacerArcadeStageNode node, string nodeId, RacerArcadeStageGraph graph, IPrototypeManager prototype)
    {
        NodeConnections.RemoveAllChildren();
        var connections = node.Connections.ToList();
        foreach (var connection in connections)
        {
            var connectionControl = new RacerEditorViewportEditNodePopupConnection(connection, nodeId, graph, prototype);
            connectionControl.OnAddPopup += OpenPopup;
            connectionControl.OnConnectionModified += args =>
            {
                node.Connections.Remove(connection); // out with the old
                node.Connections.Add(args); // and in with the new
                RefreshConnectionControls(node, nodeId, graph, prototype);
            };
            connectionControl.OnRemoveConnection += () =>
            {
                node.Connections.Remove(connection);
                RefreshConnectionControls(node, nodeId, graph, prototype);
            };
            NodeConnections.AddChild(connectionControl);
        }

    }
}
