using Content.Shared.Arcade.Racer.Stage;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.Arcade.Racer;

[GenerateTypedNameReferences]
public sealed partial class RacerEditorViewportEditNodePopupConnection : BoxContainer
{
    public event Action? OnRemoveConnection;

    public RacerEditorViewportEditNodePopupConnection(IRacerArcadeStageEdge connection) : base()
    {
        RobustXamlLoader.Load(this);

        RemoveConnection.OnPressed += _ => OnRemoveConnection?.Invoke();
    }
}
