using Content.Shared.Arcade.Racer.Stage;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.Arcade.Racer;

[GenerateTypedNameReferences]
public sealed partial class RacerEditorViewportEditEdgeNodePopup : RacerEditorViewportPopup
{
    public event Action<RacerArcadeStageEdgeNode>? OnEdgeModified;

    public RacerEditorViewportEditEdgeNodePopup(RacerArcadeStageEdgeNode edge, RacerArcadeStageGraph graph) : base()
    {
        RobustXamlLoader.Load(this);

        var i = 0;
        foreach (var nodeId in graph.Nodes.Keys)
        {
            EdgeConnection.AddItem(nodeId, i);
            EdgeConnection.SetItemMetadata(i, nodeId);

            if (edge.ConnectionId == nodeId)
                EdgeConnection.SelectId(i);

            i++;
        }
        EdgeConnection.OnItemSelected += args =>
        {
            var selected = (string)args.Button.SelectedMetadata!;
            if (edge.ConnectionId == selected)
                return;

            edge.ConnectionId = selected;
            EdgeConnection.SelectId(args.Id);
        };

        EdgeWidth.IsValid += value => value >= 0;
        EdgeWidth.Value = edge.Width;
        EdgeWidth.OnValueChanged += args =>
        {
            if (edge.Width == args.Value)
                return;

            edge.Width = args.Value;
        };

        EdgeTexture.SetTexture(edge.Texture);
        EdgeTexture.OnPopupCreated += OpenPopup;
        EdgeTexture.OnPopupRemoved += args =>
        {
            args.Close();
            RemoveChild(args);
        };
        EdgeTexture.OnTextureSelected += args =>
        {
            if (edge.Texture == args)
                return;

            edge.Texture = args;
        };

        EdgeSave.OnPressed += _ => OnEdgeModified?.Invoke(edge);
    }
}
