using Content.Shared.Arcade.Racer;
using Content.Shared.Arcade.Racer.Stage;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client.Arcade.Racer;

[GenerateTypedNameReferences]
public sealed partial class RacerEditorViewportEditEdgeStagePopup : RacerEditorViewportPopup
{
    public event Action<RacerArcadeStageEdgeStage>? OnEdgeModified;

    public RacerEditorViewportEditEdgeStagePopup(RacerArcadeStageEdgeStage edge, IPrototypeManager prototype) : base()
    {
        RobustXamlLoader.Load(this);

        if (!string.IsNullOrWhiteSpace(edge.StageId))
            Input.Text = edge.StageId;

        Input.GrabKeyboardFocus();

        Input.OnTextEntered += args =>
        {
            // no need to check if the string is empty or null as this validates it
            if (!prototype.HasIndex<RacerGameStagePrototype>(args.Text))
                return;

            edge.StageId = args.Text;
            OnEdgeModified?.Invoke(edge);
            Close();
        };
    }
}
