- type: gameMapPool
  id: DefaultMapPool
  maps:
  - Aspid
  - Atlas
  #- Amber
  - Bagel
  - Box
  - Cluster
  #- Cog
  #- Convex
  - Core
  #- Elkridge
  - Fland
  #- Gate
  - Gemini
  #- Loop
  - Marathon
  - Meta
  - Mir
  - Oasis
  - Omega
  - Saltern
  - Sparks
  - Packed
  #- Plasma
  #- Reach
  #- Train
