- type: gameMapPool
  id: DefaultMapPool
  maps:
  - Aspid
  - Atlas
  #- Amber
  - Bagel
  - Box
  - Cluster
  - Cog
  - Core
  - Fland
  #- Gate
  - Gemini
  #- Loop
  - Marathon
  - Meta
  - Mir
  - Oasis
  - Omega
  - Saltern
  - Packed
  #- Reach
  #- Train
