using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.CartridgeLoader.Cartridges;

[GenerateTypedNameReferences]
[Virtual]
public partial class BaseChatUiFragmentPopup : PanelContainer
{
    private static readonly Color BackgroundColor = Color.Black.WithAlpha(0.90f);

    public Action? OnClosePopup;

    public BaseChatUiFragmentPopup()
    {
        RobustXamlLoader.Load(this);
        ModulateSelfOverride = BackgroundColor;
        MouseFilter = MouseFilterMode.Stop;
    }
}
