using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.CartridgeLoader.Cartridges;

[GenerateTypedNameReferences]
public sealed partial class ChatUiFragmentMessageTimeHeader : BoxContainer
{
    public ChatUiFragmentMessageTimeHeader(TimeSpan time)
    {
        RobustXamlLoader.Load(this);

        Time.Text = Loc.GetString("pda-messaging-contact-time-wrapper",
            ("hours", Math.Floor(time.TotalHours)), ("minutes", $"{time.Minutes:00}"));
    }
}
