using Content.Shared.CartridgeLoader;
using Content.Shared.CartridgeLoader.Cartridges;
using Content.Shared.PDA.Messaging.Events;
using Content.Shared.PDA.Messaging.Messages;
using Content.Shared.PDA.Messaging.Recipients;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.CartridgeLoader.Cartridges;

[GenerateTypedNameReferences]
public sealed partial class ChatUiFragment : PanelContainer
{
    [Dependency] private readonly IEntityManager _entity = default!;
    private readonly BoundUserInterface _userInterface = default!;

    public Action<IChatMessage>? OnSendMessage;

    private readonly EntityUid _cartridge;
    private readonly NetEntity _netCartridge; // so much shit references it
    private ChatUiMode _uiMode;
    private IChatRecipient? _recipient;

    private IChatRecipient[] _recipients = [];

    public ChatUiFragment(BoundUserInterface userInterface, EntityUid cartridge)
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _userInterface = userInterface;
        _cartridge = cartridge;
        _netCartridge = _entity.GetNetEntity(cartridge);

        Popup.SetPositionLast();

        ChangeMode(ChatUiMode.Menu);
    }

    public void UpdateRecipients(IChatRecipient[] recipients)
    {
        _recipients = recipients;
        ChangeMode(_uiMode);
    }

    private void ChangeMode(ChatUiMode mode)
    {
        _uiMode = mode;

        Content.RemoveAllChildren();

        switch (mode)
        {
            case ChatUiMode.Menu:
                var menu = new ChatUiFragmentMenu(_recipients);
                Content.AddChild(menu);

                menu.OnRecipientClicked += recipient =>
                {
                    _recipient = recipient;
                    SendUiMessage(new PdaMessageRequestMessageHistoryMessage(_netCartridge, recipient));
                    ChangeMode(ChatUiMode.Chat);
                };
                break;
        }
    }

    private void SendUiMessage(IPdaMessagePayload payload)
    {
        var message = new ChatUiMessageEvent(payload);
        var cartridgeMessage = new CartridgeUiMessage(message);
        _userInterface.SendPredictedMessage(cartridgeMessage);
    }
}
