using Content.Client.PDA.Messaging.Messages;
using Content.Shared.PDA.Messaging.Messages;
using Content.Shared.PDA.Messaging.Recipients;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Robust.Shared.Timing;
using System.Linq;
using System.Numerics;

namespace Content.Client.CartridgeLoader.Cartridges;

[GenerateTypedNameReferences]
public sealed partial class ChatUiFragmentChat : BoxContainer, IChatUiFragmentMode
{
    [Dependency] private readonly IEntityManager _entity = default!;
    [Dependency] private readonly IClientPdaChatMessageFactory _pdaChatMessageFactory = default!;
    private readonly SpriteSystem _sprite;

    public Action<BasePdaChatMessage>? OnMessageSent;
    public Action? OnHomeButtonPressed;
    public Action? OnSettingsButtonPressed;

    public Action<BaseChatUiFragmentPopup>? OnPopupAdd { get; set; }

    private BasePdaChatMessageable _recipient = default!;
    private PdaChatRecipientProfile _profile = default!;

    private bool _isScrollingToBottom;

    public ChatUiFragmentChat()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _sprite = _entity.System<SpriteSystem>();

        HomeButton.OnPressed += _ => OnHomeButtonPressed?.Invoke();
        SettingsButton.OnPressed += _ => OnSettingsButtonPressed?.Invoke();

        TextInput.OnTextEntered += args =>
        {
            var message = new PdaChatMessageText()
            {
                Contents = args.Text,
                Sender = _profile,
                Recipient = _recipient,
            };

            OnMessageSent?.Invoke(message);

            TextInput.Clear();
        };

    }

    public void UpdateState(BasePdaChatMessageable recipient, PdaChatRecipientProfile profile, BasePdaChatMessage[] messages, IPrototypeManager prototype)
    {
        _recipient = recipient;
        _profile = profile;

        ContactIcon.Texture = _sprite.Frame0(recipient.GetUiIcon(prototype));
        ContactName.Text = Loc.GetString(recipient.GetUiName());
        ContactId.Text = Loc.GetString("pda-messaging-contact-id-wrapper", ("id", recipient.Id));

        Messages.RemoveAllChildren();

        foreach (var message in messages)
        {
            var wrapper = new ChatUiFragmentMessageWrapper(message, _pdaChatMessageFactory);
            Messages.AddChild(wrapper);
        }

        _isScrollingToBottom = messages.Any();
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);

        if (!_isScrollingToBottom)
            return;

        // not initialized
        if (Messages.Height <= 0)
            return;

        _isScrollingToBottom = false;
        var maxScroll = new Vector2(0, Messages.Height);
        Scroll.SetScrollValue(maxScroll);
    }
}
