using Content.Client.PDA.Messaging.Messages;
using Content.Shared.PDA.Messaging.Messages;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.CartridgeLoader.Cartridges;

[GenerateTypedNameReferences]
public sealed partial class ChatUiFragmentMessageWrapper : BoxContainer
{
    public ChatUiFragmentMessageWrapper(BasePdaChatMessage message)
    {
        RobustXamlLoader.Load(this);

        Sender.Text = Loc.GetString(message.Sender.GetUiName());

        var control = ((IClientPdaChatMessage)message).GetUiControl();
        Content.AddChild(control);
    }
}
