using Content.Shared.PDA.Messaging.Recipients;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.CartridgeLoader.Cartridges;

[GenerateTypedNameReferences]
public sealed partial class ChatUiFragmentSettings : BoxContainer, IChatUiFragmentMode
{
    public Action<BasePdaChatMessageable>? OnBackButtonPressed;
    public Action? OnHomeButtonPressed;

    public Action<BaseChatUiFragmentPopup>? OnPopupAdd { get; set; }

    private BasePdaChatMessageable? _recipient;

    public ChatUiFragmentSettings()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        HomeButton.OnPressed += _ => OnHomeButtonPressed?.Invoke();
        BackButton.OnPressed += _ => OnBackButtonPressed?.Invoke(_recipient!);
        ProfileIconSelector.OnNewPopup += popup => OnPopupAdd?.Invoke(popup);
    }

    public void UpdateState(PdaChatRecipientProfile profile, BasePdaChatMessageable? recipient)
    {
        _recipient = recipient;
        BackButton.Visible = recipient != null;

        ProfileIconSelector.CurrentPicture = profile.Picture;
        ProfileName.Text = Loc.GetString(profile.GetUiName());
    }
}
