using Content.Shared.PDA.Messaging.Recipients;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client.CartridgeLoader.Cartridges;

[GenerateTypedNameReferences]
public sealed partial class ChatUiFragmentMenu : BoxContainer, IChatUiFragmentMode
{
    [Dependency] private readonly IEntityManager _entity = default!;

    public Action<BasePdaChatMessageable>? OnRecipientClicked;

    public ChatUiFragmentMenu(IEnumerable<BasePdaChatMessageable> recipients, IPrototypeManager prototype)
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        var sprite = _entity.System<SpriteSystem>();

        foreach (var recipient in recipients)
        {
            var entry = new ChatUiFragmentContactEntry(recipient, prototype, sprite);
            Recipients.AddChild(entry);

            entry.OnPressed += _ => OnRecipientClicked?.Invoke(recipient);
        }
    }
}
