using System.Linq;
using System.Numerics;
using Content.Client.PDA.Messaging.Messages;
using Content.Shared.PDA.Messaging.Messages;
using Content.Shared.PDA.Messaging.Recipients;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Robust.Shared.Timing;

namespace Content.Client.CartridgeLoader.Cartridges;

[GenerateTypedNameReferences]
public sealed partial class ChatUiFragmentChat : BoxContainer, IChatUiFragmentMode
{
    [Dependency] private readonly IEntityManager _entity = default!;
    [Dependency] private readonly IClientPdaChatMessageFactory _pdaChatMessageFactory = default!;

    public Action<BasePdaChatMessage>? OnMessageSent;

    public Action? OnHomeButtonPressed;

    private bool _isScrollingToBottom;

    public ChatUiFragmentChat(BasePdaChatMessageable recipient, PdaChatRecipientProfile profile, BasePdaChatMessage[] messages, IPrototypeManager prototype)
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        var sprite = _entity.System<SpriteSystem>();

        ContactIcon.Texture = sprite.Frame0(recipient.GetUiIcon(prototype));
        ContactName.Text = Loc.GetString(recipient.GetUiName());
        ContactId.Text = Loc.GetString("pda-messaging-contact-id-wrapper", ("id", recipient.Id));

        TextInput.OnTextEntered += args =>
        {
            var message = new PdaChatMessageText()
            {
                Contents = args.Text,
                Sender = profile,
                Recipient = recipient,
            };

            OnMessageSent?.Invoke(message);

            TextInput.Clear();
        };

        HomeButton.OnPressed += _ => OnHomeButtonPressed?.Invoke();

        foreach (var message in messages)
        {
            var wrapper = new ChatUiFragmentMessageWrapper(message, _pdaChatMessageFactory);
            Messages.AddChild(wrapper);
        }

        _isScrollingToBottom = messages.Any();
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);

        if (!_isScrollingToBottom)
            return;

        // not initialized
        if (Messages.Height <= 0)
            return;

        _isScrollingToBottom = false;
        var maxScroll = new Vector2(0, Messages.Height);
        Scroll.SetScrollValue(maxScroll);
    }
}
