using Content.Shared.PDA.Messaging.Recipients;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client.CartridgeLoader.Cartridges;

[GenerateTypedNameReferences]
public sealed partial class ChatUiFragmentMenu : BoxContainer, IChatUiFragmentMode
{
    [Dependency] private readonly IEntityManager _entity = default!;
    private readonly SpriteSystem _sprite;

    public event Action<BasePdaChatMessageable>? OnRecipientClicked;
    public event Action? OnSettingsButtonPressed;

    public event Action<BaseChatUiFragmentPopup>? OnPopupAdd;

    public ChatUiFragmentMenu()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _sprite = _entity.System<SpriteSystem>();

        SettingsButton.OnPressed += _ => OnSettingsButtonPressed?.Invoke();
    }

    public void UpdateState(IEnumerable<BasePdaChatMessageable> recipients, IPrototypeManager prototype)
    {
        Recipients.RemoveAllChildren();

        foreach (var recipient in recipients)
        {
            var entry = new ChatUiFragmentContactEntry(recipient, prototype, _sprite);
            Recipients.AddChild(entry);

            entry.OnPressed += _ => OnRecipientClicked?.Invoke(recipient);
        }
    }
}
