using Content.Shared.PDA.Messaging.Messages;
using Content.Shared.PDA.Messaging.Recipients;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client.CartridgeLoader.Cartridges;

[GenerateTypedNameReferences]
public sealed partial class ChatUiFragmentChat : BoxContainer, IChatUiFragmentMode
{
    [Dependency] private readonly IEntityManager _entity = default!;

    public Action<IPdaChatRecipient>? OnRecipientClicked;

    public ChatUiFragmentChat(IPdaChatRecipient recipient, BasePdaChatMessage[] messages, IPrototypeManager prototype)
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        var sprite = _entity.System<SpriteSystem>();

        ContactIcon.Texture = sprite.Frame0(recipient.GetUiIcon(prototype));
        ContactName.Text = Loc.GetString(recipient.GetUiName());

        foreach (var message in messages)
        {
            var wrapper = new ChatUiFragmentMessageWrapper(message);
            Messages.AddChild(wrapper);
        }
    }
}
