using Content.Shared.PDA.Messaging.Recipients;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.CartridgeLoader.Cartridges;

[GenerateTypedNameReferences]
public sealed partial class ChatUiFragmentSettings : BoxContainer, IChatUiFragmentMode
{
    public Action<BasePdaChatMessageable>? OnBackButtonPressed;
    public Action? OnHomeButtonPressed;

    private BasePdaChatMessageable? _recipient;

    public ChatUiFragmentSettings()
    {
        RobustXamlLoader.Load(this);

        HomeButton.OnPressed += _ => OnHomeButtonPressed?.Invoke();
        BackButton.OnPressed += _ => OnBackButtonPressed?.Invoke(_recipient!);
    }

    public void UpdateState(BasePdaChatMessageable? recipient)
    {
        _recipient = recipient;
        BackButton.Visible = recipient != null;
    }
}
