using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.CartridgeLoader.Cartridges;

[GenerateTypedNameReferences]
public sealed partial class ChatUiFragmentSettingsHeader : BoxContainer
{
    public string? Text
    {
        get => _text;
        set
        {
            _text = value;
            HeaderText.Text = value;
        }
    }

    private string? _text;

    public ChatUiFragmentSettingsHeader()
    {
        RobustXamlLoader.Load(this);
    }
}
