using System.Collections.Frozen;
using Content.Shared.PDA.Messaging;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client.CartridgeLoader.Cartridges;

[GenerateTypedNameReferences]
public sealed partial class ChatUiFragmentProfilePictureSelectorPopup : BaseChatUiFragmentPopup
{
    public ChatUiFragmentProfilePictureSelectorPopup(FrozenDictionary<ProtoId<PdaChatProfilePicturePrototype>, PdaChatProfilePicturePrototype> pictures, SpriteSystem sprite)
    {
        RobustXamlLoader.Load(this);

        var gridSize = GetGridSize(pictures.Count);
        Grid.Rows = gridSize.X;
        Grid.Columns = gridSize.Y;

        foreach (var (id, proto) in pictures)
        {
            var button = new ChatUiFragmentProfilePictureSelectorPopupButton(proto, sprite);
            Grid.AddChild(button);

            button.OnPressed += _ => OnClosePopup?.Invoke();
        }
    }

    private static Vector2i GetGridSize(int count)
    {
        var sqrt = (float)MathF.Sqrt(count);
        var x = MathF.Ceiling(sqrt);
        var y = MathF.Ceiling(count / x);
        return new((int)x, (int)y);
    }
}
