using Content.Shared.PDA.Messaging.Recipients;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client.CartridgeLoader.Cartridges;

[GenerateTypedNameReferences]
public sealed partial class ChatUiFragmentContactEntry : Button
{
    public ChatUiFragmentContactEntry(BasePdaChatMessageable recipient, IPrototypeManager prototype, SpriteSystem sprite)
    {
        RobustXamlLoader.Load(this);

        Icon.Texture = sprite.Frame0(recipient.GetUiIcon(prototype));
        Label.Text = Loc.GetString(recipient.GetUiName());
    }
}
