using Content.Client.PDA.Messaging.Messages;
using Content.Shared.PDA.Messaging.Messages;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.CartridgeLoader.Cartridges;

[GenerateTypedNameReferences]
public sealed partial class ChatUiFragmentMessageWrapper : BoxContainer
{
    public ChatUiFragmentMessageWrapper(BasePdaChatMessage message, IClientPdaChatMessageFactory pdaChatMessageFactory)
    {
        RobustXamlLoader.Load(this);

        SenderName.Text = Loc.GetString(message.Sender.GetUiName());
        SenderId.Text = Loc.GetString("pda-messaging-contact-id-wrapper", ("id", message.Sender.Id));

        var client = pdaChatMessageFactory.Create(message);
        var control = client.GetUiControl();
        Content.AddChild(control);
    }
}
