using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;

namespace Content.Client.CartridgeLoader.Cartridges;

[GenerateTypedNameReferences]
public sealed partial class ChatUiFragmentContactEntryUnreadMarker : PanelContainer
{
    [Dependency] private readonly IEntityManager _entity = default!;

    private const string TexturePath = "/Textures/Interface/PdaMessaging/notification-circle.png";
    private static readonly ResPath Path = new(TexturePath);
    private static readonly SpriteSpecifier IconSprite = new SpriteSpecifier.Texture(Path);

    public ChatUiFragmentContactEntryUnreadMarker()
    {
        RobustXamlLoader.Load(this);

        IoCManager.InjectDependencies(this);

        var sprite = _entity.System<SpriteSystem>();
        Icon.Texture = sprite.Frame0(IconSprite);

        UpdateUnreadCount(0);
    }

    public void UpdateUnreadCount(int count)
    {
        UnreadCount.Text = Loc.GetString("pda-messaging-contact-unread-count-wrapper", ("count", count));
        Visible = count > 0;
    }
}
