using System.Collections.Frozen;
using System.Numerics;
using Content.Shared.PDA.Messaging;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client.CartridgeLoader.Cartridges;

[GenerateTypedNameReferences]
public sealed partial class ChatUiFragmentProfilePictureSelectorPopup : BaseChatUiFragmentPopup
{
    public ChatUiFragmentProfilePictureSelectorPopup(FrozenDictionary<ProtoId<PdaChatProfilePicturePrototype>, PdaChatProfilePicturePrototype> pictures, SpriteSystem sprite)
    {
        RobustXamlLoader.Load(this);

        foreach (var (id, proto) in pictures)
        {
            var button = new ChatUiFragmentProfilePictureSelectorPopupButton(proto, sprite);
            Grid.AddChild(button);

            button.OnPressed += _ => OnClosePopup?.Invoke();
        }
    }

    protected override Vector2 MeasureOverride(Vector2 availableSize)
    {
        var size = base.MeasureOverride(availableSize);
        Grid.MaxGridWidth = size.X;
        Grid.MaxGridHeight = size.Y;
        return size;
    }
}
