using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;

namespace Content.Client.CartridgeLoader.Cartridges;

[GenerateTypedNameReferences]
public sealed partial class ChatUiFragmentSettingsButton : ContainerButton
{
    [Dependency] private readonly IEntityManager _entity = default!;

    private const string TexturePath = "/Textures/Interface/VerbIcons/settings.svg.192dpi.png";
    private static readonly ResPath Path = new(TexturePath);
    private static readonly SpriteSpecifier IconSprite = new SpriteSpecifier.Texture(Path);

    public ChatUiFragmentSettingsButton()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        var sprite = _entity.System<SpriteSystem>();
        Icon.Texture = sprite.Frame0(IconSprite);
    }
}
