using Content.Shared.PDA.Messaging;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.CartridgeLoader.Cartridges;

[GenerateTypedNameReferences]
public sealed partial class ChatUiFragmentProfilePictureSelectorPopupButton : ContainerButton
{
    public ChatUiFragmentProfilePictureSelectorPopupButton(PdaChatProfilePicturePrototype picture, SpriteSystem sprite)
    {
        RobustXamlLoader.Load(this);

        Icon.Texture = sprite.Frame0(picture.Sprite);
        ToolTip = Loc.GetString(picture.Name);
    }
}
