using Content.Shared.CartridgeLoader.Cartridges;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Input;
using System.Numerics;

namespace Content.Client.CartridgeLoader.Cartridges;

[GenerateTypedNameReferences]
public sealed partial class PowerTwoUiFragment : BoxContainer
{
    private Vector2 _dragStart;

    public Action<PowerTwoDirection>? OnDragged;

    public PowerTwoUiFragment() : base()
    {
        RobustXamlLoader.Load(this);
        MouseFilter = MouseFilterMode.Stop;
    }

    public void UpdateState(int?[] grid, Vector2i gridSize, int maxValue)
    {
        GameGridRows.RemoveAllChildren();

        for (var y = 0; y < gridSize.Y; y++)
        {
            var row = new PowerTwoUiGridRow();

            for (var x = 0; x < gridSize.X; x++)
            {
                var index = SharedPowerTwoCartridgeSystem.ConvertToFlattenedIndex(new(x, y), gridSize);
                var value = grid[index];
                var cell = new PowerTwoUiCell(value, maxValue);
                row.AddChild(cell);
            }

            GameGridRows.AddChild(row);
        }
    }

    protected override void KeyBindDown(GUIBoundKeyEventArgs args)
    {
        base.KeyBindDown(args);

        if (args.Function != EngineKeyFunctions.UIClick)
            return;

        _dragStart = args.RelativePosition;
    }

    protected override void KeyBindUp(GUIBoundKeyEventArgs args)
    {
        base.KeyBindUp(args);

        if (args.Function != EngineKeyFunctions.UIClick)
            return;

        var delta = args.RelativePosition - _dragStart;
        var direction = delta.GetPowerTwoDir();
        OnDragged?.Invoke(direction);
    }
}
