using Content.Client.Message;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.CartridgeLoader.Cartridges;

[GenerateTypedNameReferences]
public sealed partial class PowerTwoUiPopup : PanelContainer
{
    private static readonly Color BackgroundColor = Color.Black.WithAlpha(0.95f);

    public PowerTwoUiPopup(string text, TimeSpan timeTaken)
    {
        RobustXamlLoader.Load(this);
        ModulateSelfOverride = BackgroundColor;

        var timeText = Loc.GetString("power-two-popup-time", ("minutes", MathF.Floor(timeTaken.Minutes)), ("seconds", timeTaken.Seconds));
        Time.SetMarkup(timeText);
        Header.SetMarkup(text);
    }
}
