using Content.Shared.CartridgeLoader.Cartridges;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.CartridgeLoader.Cartridges;

[GenerateTypedNameReferences]
public sealed partial class PowerTwoUiFragment : BoxContainer
{
    public PowerTwoUiFragment() : base()
    {
        RobustXamlLoader.Load(this);
    }

    public void UpdateState(int?[] grid, Vector2i gridSize, int maxValue)
    {
        GameGridRows.RemoveAllChildren();

        for (var y = 0; y < gridSize.Y; y++)
        {
            var row = new PowerTwoUiGridRow();

            for (var x = 0; x < gridSize.X; x++)
            {
                var index = SharedPowerTwoCartridgeSystem.ConvertToFlattenedIndex(new(x, y), gridSize);
                var value = grid[index];
                var cell = new PowerTwoUiCell(value, maxValue);
                row.AddChild(cell);
            }

            GameGridRows.AddChild(row);
        }
    }
}
