using Content.Client.Message;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.CartridgeLoader.Cartridges;

[GenerateTypedNameReferences]
public sealed partial class PowerTwoUiCell : PanelContainer
{
    private static readonly Color NoValueColor = Color.Wheat;
    private static readonly Color MinColor = Color.Yellow;
    private static readonly Color MaxColor = Color.OrangeRed;

    public PowerTwoUiCell(int? value, int maxValue)
    {
        RobustXamlLoader.Load(this);

        if (value == null)
        {
            ValueText.Text = null;
            Cell.ModulateSelfOverride = NoValueColor;
        }
        else
        {
            var text = Loc.GetString("power-two-cell-value-wrapper", ("value", value.Value));
            ValueText.SetMarkup(text);

            var color = Color.InterpolateBetween(MinColor, MaxColor, value.Value / maxValue);
            Cell.ModulateSelfOverride = color;
        }
    }
}
