using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.CartridgeLoader.Cartridges;

[GenerateTypedNameReferences]
public sealed partial class PowerTwoUiNewGameButton : Button
{
    public PowerTwoUiNewGameButton()
    {
        RobustXamlLoader.Load(this);
    }
}
