using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.PDA.Messaging.Messages.Controls;

[GenerateTypedNameReferences]
public sealed partial class PdaChatMessageTextControl : PanelContainer
{
    public PdaChatMessageTextControl(string content)
    {
        RobustXamlLoader.Load(this);

        Content.Text = content;
    }
}
