using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;

namespace Content.Client.HealthAnalyzer.UI;

[GenerateTypedNameReferences]
public sealed partial class HealthAnalyzerBodyProgressBar : PanelContainer
{
    public HealthAnalyzerBodyProgressBar()
    {
    }
}
