using Content.Shared.Holodeck;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client.Holodeck.Ui;

[GenerateTypedNameReferences]
public sealed partial class HolodeckScenarioButton : ContainerButton
{
    public HolodeckScenarioButton(ProtoId<HolodeckScenarioPrototype> scenarioId, IPrototypeManager prototype)
    {
        RobustXamlLoader.Load(this);
    }
}
