using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.Modules.ModSuit;

[GenerateTypedNameReferences]
public sealed partial class ModSuitSealableAllButton : PanelContainer
{
    public ModSuitSealableAllButton(bool isSealed)
    {
        RobustXamlLoader.Load(this);
        ButtonButton.Pressed = isSealed;
    }
}
