using Content.Shared.Modules.ModSuit;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.Modules.ModSuit;

[GenerateTypedNameReferences]
public sealed partial class ModSuitWindow : DefaultWindow
{
    public ModSuitWindow()
    {
        RobustXamlLoader.Load(this);
    }

    public void UpdateSealed(ModSuitSealableBoundUserInterfaceState state)
    {
    }
}
