using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.Modules.ModSuit;

[GenerateTypedNameReferences]
public sealed partial class ModSuitSealableButton : PanelContainer
{
    [Dependency] private readonly IEntityManager _entity = default!;

    public ModSuitSealableButton(NetEntity sealable, bool isSealed)
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        var uid = _entity.GetEntity(sealable);
        ButtonName.Text = _entity.GetComponent<MetaDataComponent>(uid).EntityName;
        ButtonButton.Pressed = isSealed;
    }
}
