using Content.Shared.Modules.ModSuit;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using System.Linq;

namespace Content.Client.Modules.ModSuit;

[GenerateTypedNameReferences]
public sealed partial class ModSuitWindow : DefaultWindow
{
    private Dictionary<NetEntity, ModSuitSealableBuiEntry> _sealableParts = [];

    public ModSuitWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
    }

    public void Refresh()
    {
        RefreshSealableIcons();
    }

    #region Sealable

    public void UpdateSealed(ModSuitSealableBoundUserInterfaceState state)
    {
        _sealableParts = state.Parts;
        RefreshSealableIcons();
    }

    internal void RefreshSealableIcons()
    {
        SealContainer.Visible = _sealableParts.Any();
        SealPanel.RemoveAllChildren();

        foreach (var (part, data) in _sealableParts)
        {
            var spriteView = new ModSuitSealableSprite(part, data.Sprite[data.IsSealed]);
            SealPanel.AddChild(spriteView);
        }
    }

    #endregion
}
