using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Graphics.RSI;
using Robust.Shared.Utility;

namespace Content.Client.Modules.ModSuit;

[GenerateTypedNameReferences]
public sealed partial class ModSuitSealableSprite : PanelContainer
{
    [Dependency] private readonly IEntityManager _entity = default!;
    private readonly SpriteSystem _sprite;

    public ModSuitSealableSprite(NetEntity sealable, SpriteSpecifier sprite)
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        _sprite = _entity.System<SpriteSystem>();

        var state = _sprite.RsiStateLike(sprite);
        PartSprite.Texture = state.GetFrame(RsiDirection.South, 0);
    }
}
