- type: entity
  id: BaseOrganHeart
  abstract: true
  components:
  - type: Sprite
    layers:
    - state: heart-on
      map: [ "enum.ToggleableVisuals.Layer" ]
  - type: Item
    size: Small
    heldPrefix: heart
  - type: Appearance
  - type: GenericVisualizer
    visuals:
      enum.ToggleableVisuals.Enabled:
        enum.ToggleableVisuals.Layer:
          True: { state: heart-on }
          False: { state: heart-off }
  - type: Organ
    organType: Heart
  - type: BodyDamageable
  - type: BodyDamageThresholds
    thresholds:
      Alive: 0
      Wounded: 10
      Dead: 120
  - type: BodyDamageOnRot
    minRotStage: 1
    fullyRottenDamage: 120
  # The heart 'metabolizes' medicines and poisons that aren't filtered out by other organs.
  # This is done because these chemicals need to have some effect even if they aren't being filtered out of your body.
  # You're technically 'immune to poison' without a heart, but.. uhh, you'll have bigger problems on your hands.
  - type: Metabolizer
    maxReagents: 2
    metabolizerTypes:
      - Human
    groups:
    - id: Medicine
    - id: Poison
    - id: Narcotic
  - type: ItemToggle
    activated: true # beating by default
    onActivate: false
  - type: ItemToggleExamineText
    enabledText: heart-examine-beating
    disabledText: heart-examine-not-beating
  - type: ItemToggleOnBodyDamage
    requiredStates:
    - Dead
  - type: OrganRequiredForDefibrillation
  - type: OrganRequiredForRespiration
  - type: DisableRespireOnItemToggle
  - type: RespirationDelayOnBodyDamage
    requiredStates:
    - Wounded
    - Dead
  - type: Temperature
  - type: Perishable
    rotAfter: 360
    molsPerSecondPerUnitMass: 0

- type: entity
  id: BaseOrganStomach
  abstract: true
  components:
  - type: Sprite
    state: stomach
  - type: Item
    size: Small
    heldPrefix: stomach
  - type: Organ
    organType: Stomach
  - type: BodyDamageable
  - type: BodyDamageThresholds
    thresholds:
      Alive: 0
      Wounded: 10
      Dead: 100
  - type: BodyDamageOnRot
    minRotStage: 1
    fullyRottenDamage: 100
  - type: VomitOnBodyDamage
    requiredStates:
    - Wounded
    - Dead
    minProb: 0.005
    maxProb: 0.5
    scaleProbToDamage: 100
  - type: SolutionContainerManager
    solutions:
      stomach:
        maxVol: 50
      food:
        maxVol: 5
        reagents:
        - ReagentId: UncookedAnimalProteins
          Quantity: 5
  - type: Stomach
  # The stomach metabolizes stuff like foods and drinks.
  # TODO: Have it work off of the ent's solution container, and move this
  # to intestines instead.
  - type: Metabolizer
    # mm yummy
    maxReagents: 3
    metabolizerTypes:
    - Human
    groups:
    - id: Food
    - id: Drink
  - type: Temperature
  - type: Perishable
    rotAfter: 780
    molsPerSecondPerUnitMass: 0
