# TODO: Add descriptions (many)
# TODO BODY: Part damage
- type: entity
  id: BasePart
  parent: BaseItem
  name: "body part"
  abstract: true
  components:
  - type: BodyPart
  - type: Gibbable
  - type: ContainerContainer
    containers:
      bodypart: !type:Container
        ents: []
  - type: StaticPrice
    price: 100
  - type: Tag
    tags:
      - Trash

- type: entity
  id: BaseTorso
  name: "torso"
  parent: BasePart
  abstract: true
  components:
  - type: BodyPart
    partType: Torso
  - type: Damageable
    damageContainer: Biological

- type: entity
  id: BaseHead
  name: "head"
  parent: BasePart
  abstract: true
  components:
  - type: BodyPart
    partType: Head
    vital: true
    overallDamageScale: 1.3
    missProb: 0.6
  - type: Input
    context: "ghost"
  - type: Damageable
    damageContainer: Biological
  - type: Tag
    tags:
      - Head

- type: entity
  id: BaseLeftArm
  name: "left arm"
  parent: BasePart
  abstract: true
  components:
  - type: BodyPart
    partType: Arm
    symmetry: Left
    overallDamageScale: 0.8
    missProb: 0.5
  - type: Damageable
    damageContainer: Biological

- type: entity
  id: BaseRightArm
  name: "right arm"
  parent: BasePart
  abstract: true
  components:
  - type: BodyPart
    partType: Arm
    symmetry: Right
    overallDamageScale: 0.8
    missProb: 0.5
  - type: Damageable
    damageContainer: Biological

- type: entity
  id: BaseLeftHand
  name: "left hand"
  parent: BasePart
  abstract: true
  components:
  - type: BodyPart
    partType: Hand
    symmetry: Left

- type: entity
  id: BaseRightHand
  name: "right hand"
  parent: BasePart
  abstract: true
  components:
  - type: BodyPart
    partType: Hand
    symmetry: Right

- type: entity
  id: BaseLeftLeg
  name: "left leg"
  parent: BasePart
  abstract: true
  components:
  - type: BodyPart
    partType: Leg
    symmetry: Left
    missProb: 0.4
  - type: MovementBodyPart
    overallDamageScale: 0.8
  - type: Damageable
    damageContainer: Biological

- type: entity
  id: BaseRightLeg
  name: "right leg"
  parent: BasePart
  abstract: true
  components:
  - type: BodyPart
    partType: Leg
    symmetry: Right
    missProb: 0.4
  - type: MovementBodyPart
    overallDamageScale: 0.8
  - type: Damageable
    damageContainer: Biological


- type: entity
  id: BaseLeftFoot
  name: "left foot"
  parent: BasePart
  abstract: true
  components:
  - type: BodyPart
    partType: Foot
    symmetry: Left


- type: entity
  id: BaseRightFoot
  name: "right foot"
  parent: BasePart
  abstract: true
  components:
  - type: BodyPart
    partType: Foot
    symmetry: Right
