# TODO: Add descriptions (many)
# TODO BODY: Part damage
- type: entity
  id: BasePart
  parent: BaseItem
  name: "body part"
  abstract: true
  components:
  - type: BodyPart
  - type: Gibbable
  - type: ContainerContainer
    containers:
      bodypart: !type:Container
        ents: []
  - type: StaticPrice
    price: 100
  - type: Tag
    tags:
      - Trash

- type: entity
  id: BaseTorso
  name: "torso"
  parent: BasePart
  abstract: true
  components:
  - type: BodyPart
    partType: Torso
    vital: true
  - type: Damageable
    damageContainer: Biological
  - type: BodyPartThresholds
    thresholds:
      Healthy: 0
      Damaged: 15
      Dead: 100
  - type: OrganReplaceable
  - type: SurgeryReceiver
    availableSurgeries:
    - OrganManipulation
    - SexReasignment
  - type: HealthAnalyzerBodyItem
    progressBarLocation: TopLeft
    sprites:
      hoverSprite:
        sprite: /Textures/Interface/health_analyzer_body.rsi
        state: torso-hover
      selectedSprite:
        sprite: /Textures/Interface/health_analyzer_body.rsi
        state: torso
  - type: UserInterface
    interfaces:
      enum.OrganSelectionUiKey.Key:
        type: OrganSelectionBoundUserInterface

- type: entity
  id: BaseHead
  name: "head"
  parent: BasePart
  abstract: true
  components:
  - type: BodyPart
    partType: Head
    vital: true
    overallDamageScale: 1.3
    missProb: 0.6
  - type: BodyPartThresholds
    thresholds:
      Healthy: 0
      Damaged: 10
      Dead: 75
  - type: OrganReplaceable
  - type: SurgeryReceiver
    availableSurgeries:
    - LimbAmputation
    - OrganManipulation
  - type: HealthAnalyzerBodyItem
    progressBarLocation: TopRight
    sprites:
      hoverSprite:
        sprite: /Textures/Interface/health_analyzer_body.rsi
        state: head-hover
      selectedSprite:
        sprite: /Textures/Interface/health_analyzer_body.rsi
        state: head
  - type: UserInterface
    interfaces:
      enum.OrganSelectionUiKey.Key:
        type: OrganSelectionBoundUserInterface
  - type: Input
    context: "ghost"
  - type: Damageable
    damageContainer: Biological
  - type: Tag
    tags:
      - Head

- type: entity
  id: BaseLeftArm
  name: "left arm"
  parent: BasePart
  abstract: true
  components:
  - type: BodyPart
    partType: Arm
    symmetry: Left
    overallDamageScale: 0.8
    missProb: 0.5
  - type: BodyPartThresholds
    thresholds:
      Healthy: 0
      Damaged: 5
      Dead: 50
  - type: Damageable
    damageContainer: Biological
  - type: SurgeryReceiver
    availableSurgeries:
    - LimbAmputation
  - type: HealthAnalyzerBodyItem
    progressBarLocation: MiddleLeft
    sprites:
      hoverSprite:
        sprite: /Textures/Interface/health_analyzer_body.rsi
        state: l_arm-hover
      selectedSprite:
        sprite: /Textures/Interface/health_analyzer_body.rsi
        state: l_arm

- type: entity
  id: BaseRightArm
  name: "right arm"
  parent: BasePart
  abstract: true
  components:
  - type: BodyPart
    partType: Arm
    symmetry: Right
    overallDamageScale: 0.8
    missProb: 0.5
  - type: BodyPartThresholds
    thresholds:
      Healthy: 0
      Damaged: 5
      Dead: 50
  - type: Damageable
    damageContainer: Biological
  - type: SurgeryReceiver
    availableSurgeries:
    - LimbAmputation
  - type: HealthAnalyzerBodyItem
    progressBarLocation: MiddleRight
    sprites:
      hoverSprite:
        sprite: /Textures/Interface/health_analyzer_body.rsi
        state: r_arm-hover
      selectedSprite:
        sprite: /Textures/Interface/health_analyzer_body.rsi
        state: r_arm

- type: entity
  id: BaseLeftHand
  name: "left hand"
  parent: BasePart
  abstract: true
  components:
  - type: BodyPart
    partType: Hand
    symmetry: Left

- type: entity
  id: BaseRightHand
  name: "right hand"
  parent: BasePart
  abstract: true
  components:
  - type: BodyPart
    partType: Hand
    symmetry: Right

- type: entity
  id: BaseLeftLegNoDamage
  name: "left leg"
  parent: BasePart
  abstract: true
  components:
  - type: BodyPart
    partType: Leg
    symmetry: Left
    missProb: 0.4
    overallDamageScale: 0.8
  - type: MovementBodyPart

- type: entity
  id: BaseLeftLeg
  name: "left leg"
  parent: BaseLeftLegNoDamage
  abstract: true
  components:
  - type: BodyPartThresholds
    thresholds:
      Healthy: 0
      Damaged: 5
      Dead: 65
  - type: Damageable
    damageContainer: Biological
  - type: SurgeryReceiver
    availableSurgeries:
    - LimbAmputation
  - type: HealthAnalyzerBodyItem
    progressBarLocation: BottomLeft
    sprites:
      hoverSprite:
        sprite: /Textures/Interface/health_analyzer_body.rsi
        state: l_leg-hover
      selectedSprite:
        sprite: /Textures/Interface/health_analyzer_body.rsi
        state: l_leg

- type: entity
  id: BaseRightLegNoDamage
  name: "right leg"
  parent: BasePart
  abstract: true
  components:
  - type: BodyPart
    partType: Leg
    symmetry: Right
    missProb: 0.4
    overallDamageScale: 0.8
  - type: MovementBodyPart

- type: entity
  id: BaseRightLeg
  name: "right leg"
  parent: BaseRightLegNoDamage
  abstract: true
  components:
  - type: BodyPartThresholds
    thresholds:
      Healthy: 0
      Damaged: 5
      Dead: 65
  - type: Damageable
    damageContainer: Biological
  - type: SurgeryReceiver
    availableSurgeries:
    - LimbAmputation
  - type: HealthAnalyzerBodyItem
    progressBarLocation: BottomRight
    sprites:
      hoverSprite:
        sprite: /Textures/Interface/health_analyzer_body.rsi
        state: r_leg-hover
      selectedSprite:
        sprite: /Textures/Interface/health_analyzer_body.rsi
        state: r_leg

- type: entity
  id: BaseLeftFoot
  name: "left foot"
  parent: BasePart
  abstract: true
  components:
  - type: BodyPart
    partType: Foot
    symmetry: Left


- type: entity
  id: BaseRightFoot
  name: "right foot"
  parent: BasePart
  abstract: true
  components:
  - type: BodyPart
    partType: Foot
    symmetry: Right
