using System.Numerics;
using Content.Shared.Teleportation.Components;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Client.UserInterface.Controls;

namespace Content.Client.Teleportation.Ui;

[GenerateTypedNameReferences]
public sealed partial class TeleporterConsoleUI : DefaultWindow
{

    //public HashSet<TeleporterBeacon> BeaconList = new();
    //public Vector2 Coordinates = new Vector2(0, 0);

    public event Action<NetEntity?, bool>? SendClicked;
    public event Action<NetEntity?, bool>? ReceiveClicked;
    public event Action<string>? OnCoordsXChanged;
    public event Action<string>? OnCoordsYChanged;

    public string? LinkedTeleporter;

    public TeleporterConsoleUI()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        if (LinkedTeleporter != null)
            LinkLabel.Text = LinkedTeleporter;

        //CoordsX.OnTextEntered += e => OnCoordsXChanged?.Invoke(e.Text);
        CoordsX.OnFocusExit += e => OnCoordsXChanged?.Invoke(e.Text);

        //CoordsY.OnTextEntered += e => OnCoordsYChanged?.Invoke(e.Text);
        CoordsY.OnFocusExit += e => OnCoordsYChanged?.Invoke(e.Text);

        //BeaconButton.OnPressed += _ => BeaconClicked.invoke();
        SendToButton.OnPressed += _ => SendClicked?.Invoke(NetEntity.Invalid, true);
        ReceiveFromButton.OnPressed += _ => ReceiveClicked?.Invoke(NetEntity.Invalid, false);
    }

    /*
    public void AddBeaconButtons()
    {
        foreach (var points in Warps)
        {
            var name = points.Location;
            var teleportPoint = points.TelePoint;

            var currentButtonRef = new Button
            {
                Text = name,
                TextAlign = Label.AlignMode.Right,
                HorizontalAlignment = HAlignment.Center,
                VerticalAlignment = VAlignment.Center,
                SizeFlagsStretchRatio = 1,
                MinSize = new Vector2(250, 20),
                ClipText = true,
            };

            currentButtonRef.OnPressed += _ => BeaconClicked?.Invoke(teleportPoint, name);


            TeleportButtonContainer.AddChild(currentButtonRef);
        }
    }
    */
    public void SetCoordsX(string x)
    {
        CoordsX.Text = x;
    }
    public void SetCoordsY(string y)
    {
        CoordsY.Text = y;
    }
    public void UpdateTeleportSummary(string summary)
    {
        SummaryLabel.Text = summary;
    }

}
