using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.Body;

[GenerateTypedNameReferences]
public sealed partial class OrganSelectionRow : PanelContainer
{
    public OrganSelectionRow(HashSet<OrganSelectionButton> buttons)
    {
        RobustXamlLoader.Load(this);

        foreach (var button in buttons)
        {
            OrganRow.AddChild(button);
        }
    }
}
