using Content.Shared.Body.Prototypes;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.Body;

[GenerateTypedNameReferences]
public sealed partial class OrganSelectionButton : PanelContainer
{
    public EntityUid? Organ;
    public OrganPrototype Type;

    public OrganSelectionButton(EntityUid? uid, OrganPrototype type)
    {
        RobustXamlLoader.Load(this);
        var entMan = IoCManager.Resolve<EntityManager>();
        var spriteSys = entMan.System<SpriteSystem>();

        Organ = uid;
        Type = type;

        if (uid != null && entMan.TryGetComponent<SpriteComponent>(uid.Value, out var sprite))
            Icon.Texture = sprite.Icon?.Default;
        else
            Icon.Texture = spriteSys.Frame0(Type.EmptySlotSprite);

        if (uid != null)
            OrganName.Text = entMan.GetComponent<MetaDataComponent>(uid.Value).EntityName;
        else
            OrganName.Text = Loc.GetString("organ-type-empty");

        OrganType.Text = Loc.GetString(Type.Name);
    }
}
