using Content.Shared.Body.Prototypes;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client.Body;

[GenerateTypedNameReferences]
public sealed partial class OrganSelectionButton : PanelContainer
{
    public ProtoId<OrganPrototype> Type;

    public event Action<ProtoId<OrganPrototype>>? OnOrganPressed;

    public OrganSelectionButton(EntityUid? uid, OrganPrototype type)
    {
        RobustXamlLoader.Load(this);
        Type = type;

        var entMan = IoCManager.Resolve<EntityManager>();
        var spriteSys = entMan.System<SpriteSystem>();

        if (uid != null && entMan.TryGetComponent<SpriteComponent>(uid.Value, out var sprite))
            Icon.Texture = sprite.Icon?.Default;
        else
            Icon.Texture = spriteSys.Frame0(type.EmptySlotSprite);

        if (uid != null)
            OrganName.Text = entMan.GetComponent<MetaDataComponent>(uid.Value).EntityName;
        else
            OrganName.Text = Loc.GetString("organ-name-none");

        OrganType.Text = Loc.GetString(type.Name);

        OrganButton.OnPressed += _ => OnOrganPressed?.Invoke(Type);
    }
}
