using Content.Shared.Body.Organ;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.Body;

[GenerateTypedNameReferences]
public sealed partial class OrganSelectionButton : PanelContainer
{
    public EntityUid Organ;
    public OrganType Type;

    public OrganSelectionButton(EntityUid uid, OrganType type)
    {
        RobustXamlLoader.Load(this);
        var entMan = IoCManager.Resolve<EntityManager>();

        Organ = uid;
        Type = type;

        Icon.SetEntity(uid);
        OrganName.Text = entMan.GetComponent<MetaDataComponent>(uid).EntityName;
        OrganType.Text = Loc.GetString($"organ-type-{nameof(type).ToLower()}");
    }
}
