- type: entity
  abstract: true
  id: BaseRacerVehicle
  parent: BaseRacerObject
  components:
  - type: RacerArcadeObjectCollision
    shapes:
      ship:
        layer:
        - Track
        mask:
        - Vehicles
        shape: !type:Sphere
          radius: 1.5
  - type: RacerArcadeObjectPhysics
  - type: RacerArcadeObjectGravity
  - type: RacerArcadeObjectHover
